# Generated by Django 4.2.7 on 2023-11-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoinsMarketApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.IntegerField()),
                ('currency', models.CharField(choices=[('UAH', 'Hryvnia'), ('KP', 'Kopiyka'), ('USD', 'Dollar'), ('UC', 'USA Cent'), ('EUR', 'Euro'), ('EC', 'Euro'), ('CZK', 'Czech Koruna'), ('HL', 'Czech Heller'), ('PLN', 'Zloty'), ('GR', 'Grosz')], max_length=3)),
                ('year', models.IntegerField()),
                ('material', models.CharField(choices=[('S', 'Silver'), ('G', 'Gold'), ('N', 'Nickel'), ('A', 'Antimony'), ('B', 'Bronze'), ('C', 'Cupronickel'), ('Cp', 'Copper'), ('Br', 'Brass')], max_length=2)),
                ('description', models.CharField(max_length=200)),
                ('image_obverse', models.ImageField(upload_to='obverses/')),
                ('image_reverse', models.ImageField(upload_to='reverses/')),
                ('weight', models.FloatField()),
                ('diameter', models.FloatField()),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoinsMarketApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='DealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lhs', models.IntegerField()),
                ('rhs', models.IntegerField()),
                ('price', models.IntegerField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoinsMarketApp.coin')),
            ],
        ),
    ]
