# Generated by Django 4.2.7 on 2023-11-23 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinsMarketApp', '0003_alter_coin_diameter_alter_coin_par_alter_coin_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealhistory',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='dealhistory',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
