# Generated by Django 4.2.7 on 2023-11-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinsMarketApp', '0006_alter_coin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
