# Generated by Django 4.2.7 on 2023-11-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinsMarketApp', '0007_alter_coin_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='image_obverse',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='image_reverse',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
