# Generated by Django 4.2.7 on 2023-11-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinsMarketApp', '0010_alter_coin_currency_alter_coin_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='currency',
            field=models.CharField(blank=True, choices=[('UAH', 'Hryvnia'), ('KP', 'Kopiyka'), ('USD', 'Dollar'), ('UC', 'USA Cent'), ('EUR', 'Euro'), ('EC', 'Eurocent'), ('CZK', 'Czech Koruna'), ('HL', 'Czech Heller'), ('PLN', 'Zloty'), ('GR', 'Grosz')], max_length=3),
        ),
        migrations.AlterField(
            model_name='coin',
            name='material',
            field=models.CharField(blank=True, choices=[('S', 'Silver'), ('G', 'Gold'), ('N', 'Nickel'), ('A', 'Antimony'), ('B', 'Bronze'), ('C', 'Cupronickel'), ('Cp', 'Copper'), ('Br', 'Brass')], max_length=2),
        ),
    ]
