# Generated by Django 4.2.7 on 2023-11-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinsMarketApp', '0011_alter_coin_currency_alter_coin_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
