# Generated by Django 4.2.7 on 2023-11-25 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinsMarketApp', '0014_alter_coin_currency_alter_coin_diameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='diameter',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coin',
            name='material',
            field=models.CharField(blank=True, choices=[('S', 'Silver'), ('G', 'Gold'), ('N', 'Nickel'), ('A', 'Antimony'), ('B', 'Bronze'), ('C', 'Cupronickel'), ('Cp', 'Copper'), ('Br', 'Brass')], max_length=2),
        ),
        migrations.AlterField(
            model_name='coin',
            name='weight',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
