# Generated by Django 4.2.7 on 2023-11-25 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinsMarketApp', '0015_alter_coin_diameter_alter_coin_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='diameter',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coin',
            name='image_obverse',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='image_reverse',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='material',
            field=models.CharField(choices=[('S', 'Silver'), ('G', 'Gold'), ('N', 'Nickel'), ('A', 'Antimony'), ('B', 'Bronze'), ('C', 'Cupronickel'), ('Cp', 'Copper'), ('Br', 'Brass')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='weight',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
