# Generated by Django 4.2.7 on 2023-11-25 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinsMarketApp', '0016_alter_coin_description_alter_coin_diameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.IntegerField()),
                ('operation_type', models.CharField(choices=[('A', 'Add'), ('W', 'Withdraw')], max_length=1)),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.IntegerField()),
                ('operation_type', models.CharField(choices=[('A', 'Add'), ('E', 'Edit'), ('D', 'Delete')], max_length=1)),
                ('coin_info', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='dealhistory',
            old_name='lhs',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='dealhistory',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='dealhistory',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='dealhistory',
            name='coin_info',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='dealhistory',
            name='operation_type',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='dealhistory',
            name='rhs',
            field=models.CharField(max_length=30),
        ),
    ]
